-- https://school.programmers.co.kr/learn/courses/30/lessons/131534
SELECT 
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    COUNT(DISTINCT s.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / 
        (SELECT COUNT(*) 
         FROM USER_INFO 
         WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM 
    USER_INFO u
INNER JOIN 
    ONLINE_SALE s ON u.USER_ID = s.USER_ID
WHERE 
    YEAR(u.JOINED) = 2021
GROUP BY 
    YEAR(s.SALES_DATE), 
    MONTH(s.SALES_DATE)
ORDER BY 
    YEAR, 
    MONTH;